/// <reference types="Cypress" />

describe('Cenário 005 - Exibição do campo “Agrupar por”', () => {
    beforeEach(() => {
        cy.visitAndSignIn()
    })

    it('CT005 - Exibindo campo “Agrupar por*”', () => {
        cy.visitCustomDashboard()
        cy.clickButtonAddGraphic()

        cy.get('#mat-dialog-1')
            .contains('Eixo X*')
            .click({force: true})
            .get('[role="listbox"]')
            .contains('Data da coleta da amostra')
            .click()
        cy.get('#mat-dialog-1')
            .contains('Agrupar por*')
            .should('exist')

        cy.get('#mat-dialog-1')
            .contains('Eixo X*')
            .click({force: true})
            .get('[role="listbox"]')
            .contains('Data de fabricação')
            .click()
        cy.get('#mat-dialog-1')
            .contains('Agrupar por*')
            .should('exist')

        cy.get('#mat-dialog-1')
            .contains('Eixo X*')
            .click({force: true})
            .get('[role="listbox"]')
            .contains('Data de validade')
            .click()
        cy.get('#mat-dialog-1')
            .contains('Agrupar por*')
            .should('exist')
    })

    it('CT006 - Não exibindo campo “Agrupar por*”', () => {
        cy.visitCustomDashboard()
        cy.clickButtonAddGraphic()

        cy.get('#mat-dialog-1')
            .contains('Eixo X*')
            .click({force: true})
            .get('[role="listbox"]')
            .contains('Coletor')
            .click()
        cy.get('#mat-dialog-1')
            .contains('Agrupar por*')
            .should('not.exist')

        cy.get('#mat-dialog-1')
            .contains('Eixo X*')
            .click({force: true})
            .get('[role="listbox"]')
            .contains('Coleta')
            .click()
        cy.get('#mat-dialog-1')
            .contains('Agrupar por*')
            .should('not.exist')

        cy.get('#mat-dialog-1')
            .contains('Eixo X*')
            .click({force: true})
            .get('[role="listbox"]')
            .contains('Etapa do processo')
            .click()
        cy.get('#mat-dialog-1')
            .contains('Agrupar por*')
            .should('not.exist')

        cy.get('#mat-dialog-1')
            .contains('Eixo X*')
            .click({force: true})
            .get('[role="listbox"]')
            .contains('Grupo da matriz')
            .click()
        cy.get('#mat-dialog-1')
            .contains('Agrupar por*')
            .should('not.exist')

        cy.get('#mat-dialog-1')
            .contains('Eixo X*')
            .click({force: true})
            .get('[role="listbox"]')
            .contains('Lote')
            .click()
        cy.get('#mat-dialog-1')
            .contains('Agrupar por*')
            .should('not.exist')

        cy.get('#mat-dialog-1')
            .contains('Eixo X*')
            .click({force: true})
            .get('[role="listbox"]')
            .contains('Matriz')
            .click()
        cy.get('#mat-dialog-1')
            .contains('Agrupar por*')
            .should('not.exist')

        cy.get('#mat-dialog-1')
            .contains('Eixo X*')
            .click({force: true})
            .get('[role="listbox"]')
            .contains('Metodologia')
            .click()
        cy.get('#mat-dialog-1')
            .contains('Agrupar por*')
            .should('not.exist')

        cy.get('#mat-dialog-1')
            .contains('Eixo X*')
            .click({force: true})
            .get('[role="listbox"]')
            .contains('Parâmetro')
            .click()
        cy.get('#mat-dialog-1')
            .contains('Agrupar por*')
            .should('not.exist')

        cy.get('#mat-dialog-1')
            .contains('Eixo X*')
            .click({force: true})
            .get('[role="listbox"]')
            .contains('Padrão de conformidade')
            .click()
        cy.get('#mat-dialog-1')
            .contains('Agrupar por*')
            .should('not.exist')

        cy.get('#mat-dialog-1')
            .contains('Eixo X*')
            .click({force: true})
            .get('[role="listbox"]')
            .contains('Plano de coleta')
            .click()
        cy.get('#mat-dialog-1')
            .contains('Agrupar por*')
            .should('not.exist')
        
        cy.get('#mat-dialog-1')
            .contains('Eixo X*')
            .click({force: true})
            .get('[role="listbox"]')
            .contains('Referência')
            .click()
        cy.get('#mat-dialog-1')
            .contains('Agrupar por*')
            .should('not.exist')
    })
})