/// <reference types="Cypress" />

import invoke from 'lodash/invoke'

describe('Dashboard Personalizado - Adicionar gráfico', () => {
    beforeEach(() => {
        cy.visitAndSignIn()
    })

    it('CT001', () => {
        cy.get('.mat-icon.text-white.material-icons[role="img"][data-mat-icon-type="font"]')
            .eq(0)
            .click()
        
        cy.contains('span', 'Personalizado')
            .click()
    })

    it('CT002', () => {
        cy.visitCustomDashboard()
        
        cy.get('.mat-tooltip-trigger > .bq-theme > .mat-focus-indicator')
            .click()
        
        cy.get('.dialog-form__title')
            .should('be.visible')
        
        cy.get('#mat-dialog-1')
            .contains('Colunas')
            .should('be.visible')

        cy.get('#mat-dialog-1')
            .contains('Gráfico')
            .should('be.visible')

        cy.get('#mat-dialog-1')
            .contains('Eixo X*')

        cy.get('#mat-dialog-1')
            .contains('Agrupar por*')
            .should('not.exist')

        cy.get('#mat-dialog-1')
            .contains('Eixo y*')
            .should('be.visible')

        cy.get('#mat-dialog-1')
            .contains('Número de Resultados')
            .should('be.visible')

        cy.get('#mat-dialog-1')
            .contains('Nome')
            .should('exist')

        cy.get('#mat-dialog-1')
            .contains('Salvar e Adicionar')
            .should('be.visible')
    })

    it('CT003', () => {
        cy.visitCustomDashboard()
        cy.clickButtonAddGraphic()

        cy.get('#mat-dialog-1')
            .contains('Gráfico')
            .click({force: true})

        cy.get('[role="listbox"]')
            .should('not.exist')
    })

    it('CT004', () => {
        cy.visitCustomDashboard()
        cy.clickButtonAddGraphic()

        cy.get('#mat-dialog-1')
            .contains('Eixo X*')
            .click({force: true})

        cy.get('[role="listbox"]')
            .contains('Coletor')
            .scrollIntoView()
            .should('be.visible')
        cy.get('[role="listbox"]')
            .contains('Coleta')
            .scrollIntoView()
            .should('be.visible')
        cy.get('[role="listbox"]')
            .contains('Data da coleta da amostra')
            .scrollIntoView()
            .should('be.visible')
        cy.get('[role="listbox"]')
            .contains('Data de validade')
            .scrollIntoView()
            .should('be.visible')
        cy.get('[role="listbox"]')
            .contains('Data de fabricação')
            .scrollIntoView()
            .should('be.visible')
        cy.get('[role="listbox"]')
            .contains('Etapa do processo')
            .scrollIntoView()
            .should('be.visible')
        cy.get('[role="listbox"]')
            .contains('Grupo da matriz')
            .scrollIntoView()
            .should('be.visible')
        cy.get('[role="listbox"]')
            .contains('Lote')
            .scrollIntoView()
            .should('be.visible')
        cy.get('[role="listbox"]')
            .contains('Matriz')
            .scrollIntoView()
            .should('be.visible')
        cy.get('[role="listbox"]')
            .contains('Metodologia')
            .scrollIntoView()
            .should('be.visible')
        cy.get('[role="listbox"]')
            .contains('Parâmetro')
            .scrollIntoView()
            .should('be.visible')
        cy.get('[role="listbox"]')
            .contains('Padrão de conformidade')
            .scrollIntoView()
            .should('be.visible')
        cy.get('[role="listbox"]')
            .contains('Plano de coleta')
            .scrollIntoView()
            .should('be.visible')
        cy.get('[role="listbox"]')
            .contains('Referência')
            .scrollIntoView()
            .should('be.visible')
    })

    it('CT005', () => {
        cy.visitCustomDashboard()
        cy.clickButtonAddGraphic()

        cy.get('#mat-dialog-1')
            .contains('Eixo X*')
            .click({force: true})
            .get('[role="listbox"]')
            .contains('Data da coleta da amostra')
            .click()
        cy.get('#mat-dialog-1')
            .contains('Agrupar por*')
            .should('exist')

        cy.get('#mat-dialog-1')
            .contains('Eixo X*')
            .click({force: true})
            .get('[role="listbox"]')
            .contains('Data de fabricação')
            .click()
        cy.get('#mat-dialog-1')
            .contains('Agrupar por*')
            .should('exist')

        cy.get('#mat-dialog-1')
            .contains('Eixo X*')
            .click({force: true})
            .get('[role="listbox"]')
            .contains('Data de validade')
            .click()
        cy.get('#mat-dialog-1')
            .contains('Agrupar por*')
            .should('exist')
    })

    it('CT006', () => {
        cy.visitCustomDashboard()
        cy.clickButtonAddGraphic()

        cy.get('#mat-dialog-1')
            .contains('Eixo X*')
            .click({force: true})
            .get('[role="listbox"]')
            .contains('Coletor')
            .click()
        cy.get('#mat-dialog-1')
            .contains('Agrupar por*')
            .should('not.exist')

        cy.get('#mat-dialog-1')
            .contains('Eixo X*')
            .click({force: true})
            .get('[role="listbox"]')
            .contains('Coleta')
            .click()
        cy.get('#mat-dialog-1')
            .contains('Agrupar por*')
            .should('not.exist')

        cy.get('#mat-dialog-1')
            .contains('Eixo X*')
            .click({force: true})
            .get('[role="listbox"]')
            .contains('Etapa do processo')
            .click()
        cy.get('#mat-dialog-1')
            .contains('Agrupar por*')
            .should('not.exist')

        cy.get('#mat-dialog-1')
            .contains('Eixo X*')
            .click({force: true})
            .get('[role="listbox"]')
            .contains('Grupo da matriz')
            .click()
        cy.get('#mat-dialog-1')
            .contains('Agrupar por*')
            .should('not.exist')

        cy.get('#mat-dialog-1')
            .contains('Eixo X*')
            .click({force: true})
            .get('[role="listbox"]')
            .contains('Lote')
            .click()
        cy.get('#mat-dialog-1')
            .contains('Agrupar por*')
            .should('not.exist')

        cy.get('#mat-dialog-1')
            .contains('Eixo X*')
            .click({force: true})
            .get('[role="listbox"]')
            .contains('Matriz')
            .click()
        cy.get('#mat-dialog-1')
            .contains('Agrupar por*')
            .should('not.exist')

        cy.get('#mat-dialog-1')
            .contains('Eixo X*')
            .click({force: true})
            .get('[role="listbox"]')
            .contains('Metodologia')
            .click()
        cy.get('#mat-dialog-1')
            .contains('Agrupar por*')
            .should('not.exist')

        cy.get('#mat-dialog-1')
            .contains('Eixo X*')
            .click({force: true})
            .get('[role="listbox"]')
            .contains('Parâmetro')
            .click()
        cy.get('#mat-dialog-1')
            .contains('Agrupar por*')
            .should('not.exist')

        cy.get('#mat-dialog-1')
            .contains('Eixo X*')
            .click({force: true})
            .get('[role="listbox"]')
            .contains('Padrão de conformidade')
            .click()
        cy.get('#mat-dialog-1')
            .contains('Agrupar por*')
            .should('not.exist')

        cy.get('#mat-dialog-1')
            .contains('Eixo X*')
            .click({force: true})
            .get('[role="listbox"]')
            .contains('Plano de coleta')
            .click()
        cy.get('#mat-dialog-1')
            .contains('Agrupar por*')
            .should('not.exist')
        
        cy.get('#mat-dialog-1')
            .contains('Eixo X*')
            .click({force: true})
            .get('[role="listbox"]')
            .contains('Referência')
            .click()
        cy.get('#mat-dialog-1')
            .contains('Agrupar por*')
            .should('not.exist')
    })

    it('CT007', () => {
        cy.visitCustomDashboard()
        cy.clickButtonAddGraphic()
        cy.showGroupBySelect()

        cy.get('#mat-dialog-1')
            .contains('Agrupar por*')
            .click({force: true})

        cy.get('[role="listbox"]')
            .contains('Dias')
            .should('be.visible')
        cy.get('[role="listbox"]')
            .contains('Semanas')
            .should('be.visible')
        cy.get('[role="listbox"]')
            .contains('Meses')
            .should('be.visible')
        cy.get('[role="listbox"]')
            .contains('Anos')
            .should('be.visible')
    })

    it('CT008', () => {
        cy.visitCustomDashboard()
        cy.clickButtonAddGraphic()

        cy.get('#mat-dialog-1')
            .contains('Eixo y*')
            .click({force: true})

        cy.get('[role="listbox"]')
            .should('not.exist')
    })

    it('CT009', () => {
        const longText = Cypress._.repeat('0123456789', 10)
        
        cy.visitCustomDashboard()
        cy.clickButtonAddGraphic()

        cy.get('#mat-dialog-1')
            .get('input[formcontrolname="name"]')
            .click({force: true})
            .invoke('val', longText)
            .should('have.value', longText)
            .clear()
    })

    it('CT010', () => {
        const longText = Cypress._.repeat('0123456789', 10)

        cy.visitCustomDashboard()
        cy.clickButtonAddGraphic()

        cy.get('#mat-dialog-1')
        .get('input[formcontrolname="name"]')
        .click({force: true})
        .invoke('val', longText + "a")
        .should('have.value', longText)
        //.clear()
    })

    it('CT011', () => {
        cy.visitCustomDashboard()
        cy.clickButtonAddGraphic()
        cy.showGroupBySelect()

        cy.get('#mat-dialog-1')
            .contains('Agrupar por*')
            .click({force: true})
            .get('[role="listbox"]')
            .contains('Dias')
            .click()

        cy.get('#mat-dialog-1')
            .contains('Salvar e Adicionar')
            .click()

        cy.contains('Gráfico salvo com sucesso!')
        cy.contains('Ok')
            .click()

        cy.get('app-card')
            .contains(' Total de resultados ')
            .parent()
            .contains(' Resultados Conformes ')
            .parent()
            .contains(' Resultados que atingiram o valor de alerta ')
            .parent()
            .contains(' Resultados Não Conformes ')
        cy.get('[role="img"][mattooltip="Excluir Gráfico"]')
            .click()
        cy.contains(' Excluir')
            .click()
        cy.get('mat-error')
            .should('be.visible')
        cy.contains('Gráfico excluído com sucesso!')
    })

    it('CT012', () => {
        cy.visitCustomDashboard()
        cy.clickButtonAddGraphic()
        
        cy.get('#mat-dialog-1')
            .contains('Eixo X*')
            .click({force: true})
            .get('[role="listbox"]')
            .contains('Coletor')
            .click()

        cy.get('#mat-dialog-1')
            .contains('Salvar e Adicionar')
            .click()

        cy.contains('Gráfico salvo com sucesso!')
        cy.contains('Ok')
            .click()

        cy.get('app-card')
            .contains(' Total de resultados ')
            .parent()
            .contains(' Resultados Conformes ')
            .parent()
            .contains(' Resultados que atingiram o valor de alerta ')
            .parent()
            .contains(' Resultados Não Conformes ')
        cy.get('[role="img"][mattooltip="Excluir Gráfico"]')
            .click()
        cy.contains(' Excluir')
            .click()
        cy.get('mat-error')
            .should('be.visible')
        cy.contains('Gráfico excluído com sucesso!')
    })

    it('CT013', () => { 
        cy.visitCustomDashboard()
        cy.clickButtonAddGraphic()

        cy.get('#mat-dialog-1')
            .contains('Salvar e Adicionar')
            .click()

        cy.get('#mat-dialog-1')
            .contains('Informações incompletas')

        cy.get('#mat-dialog-1')
            .get('div.mat-form-field-outline.ng-star-inserted').eq(3)
            .should('have.css', 'border-color', 'rgb(203, 0, 0)')
    })
})